language: java
jdk:
    - oraclejdk8
install: true
script: mvn install -DskipTests=true

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  api_key: ""
  file: 
    - "ShadowCommon.jar"
    - "Deps.jar"
  skip_cleanup: true
  on:
    tags: true
